---
- name: Entrega 30792 Cambio de tirilla a JS 
  hosts: all
  gather_facts: yes
  ignore_errors: True
  tasks:
   - name: Change to multitask pos linux
     shell: systemctl isolate multi-user.target
   - name: create directory Backup
     shell: mkdir -p /home/reg/ansible/Backup_Deploy_Pos
   - name: Backtup for Rollback
     shell: mv /home/reg/gd90/{{ item }} /home/reg/ansible/deployDemoJS/
     with_items:
       - class
       - jars
       - CL.SH
   - name: copy class ars
     ansible.builtin.copy:
      src: 30792/class
      dest: /home/reg/gd90/
      owner: reg
      group: users
      mode: '0754'
   - name: copy js
     ansible.builtin.copy:
      src: 30792/js/{{ item }}
      dest: /home/reg/gd90/
      owner: reg
      group: users
      mode: '0755'
     with_items:
       - FiscalLayout.js
   - name: copy jars
     ansible.builtin.copy:
      src: 30792/jars.tar.gz
      dest: /home/reg/gd90/
      owner: reg
      group: users
      mode: '0755'
   - name: copy CL.SH
     ansible.builtin.copy:
      src: 30792/CL.SH
      dest: /home/reg/gd90/
      owner: reg
      group: users
      mode: '0755'
   - name: descomprime jars
     shell: tar -xzvf /home/reg/gd90/jars.tar.gz -C /home/reg/gd90/
   - name: number of pos
     shell: hostname | sed "s/REG//g"
     register: numberpos
   - name: get version ARS
     shell:  grep -i "GdPos ARS v" /home/reg/gd90/L_JVM{{ numberpos.stdout  }}.LOG | tail -n 1
     register: arsversion
   - name: print version ARS Final
     debug: msg={{ arsversion.stdout }}
   - name: Change to graphical pos linux
     shell: systemctl isolate graphical.target
