---
- name: Deploy pos
  hosts: all
  tasks:
   - name: Search process for 7052
     shell: ps -fea | grep /home/reg/gd90/7052.SH | head -n 1 | awk '{print $2}'
     register: running_processes
   - name: Kill process ARS in POS
     ignore_errors: yes
     shell: kill -9 {{ item }}
     with_items: "{{ running_processes.stdout_lines }}"

