---
- name: Deploy pos
  hosts: 192.168.1.35
  tasks:
   - name: Change to multitask pos linux
     shell: systemctl isolate multi-user.target
   - name: copy class ars
     ansible.builtin.copy:
      src: /var/lib/rancher/k3s/storage/pvc-ab4f0ca1-836c-46dd-a24a-0b1db443090d_awx_awx-projects-claim/_14__deplay_pos/class
      dest: /home/reg/gd90/class/
      owner: reg
      group: users
      mode: '0755'
   - name: Change to graphical pos linux
     shell: systemctl isolate graphical.target

