---
- name: Deploy pos
  hosts: 192.168.1.35
  tasks:
   - name: Change to multitask pos linux
     shell: systemctl isolate multi-user.target
   - name: copy class ars
     ansible.builtin.copy:
      src: class/{{ item }}
      dest: /home/reg/gd90/class/
      owner: reg
      group: users
      mode: '0755'
     with_items:
       - ars-cla.jar
       - ars.jar
       - ars-koba.jar
   - name: copy pregs
     ansible.builtin.copy:
      src: pregs/{{ item }}
      dest: /home/reg/gd90/
      owner: reg
      group: users
      mode: '0755'
     with_items:
       - P_REGCONF.hierarchy.1500.GiftCard.XML
       - P_REGCONF.hierarchy.8000.Retiros.XML
       - P_REGCONF.hierarchy.ReprintReceipt.XML
       - P_REGEVENT.XML
   - name: copy jars
     ansible.builtin.copy:
      src: jars/{{ item }}
      dest: /home/reg/gd90/jars/
      owner: reg
      group: users
      mode: '0755'
     with_items:
       - BridgeFiscalToPrinter.jar
       - core-2.0.jar
       - hashids-1.0.3.jar
       - idcreader-dc.jar
       - idcreader-dc-shared.jar
       - JposUtils.jar
       - libutils.jar
   - name: copy js
     ansible.builtin.copy:
      src: js/{{ item }}
      dest: /home/reg/gd90/js/
      owner: reg
      group: users
      mode: '0755'
     with_items:
       - AdditionalHeaderVoucherDigital.js
       - TiqueteReducido.js
   - name: copy js
     ansible.builtin.copy:
      src: sh/{{ item }}
      dest: /home/reg/gd90/sh/
      owner: reg
      group: users
      mode: '0755'
     with_items:
       - ValidateJposDT.sh
   - name: copy lista-jpos
     ansible.builtin.copy:
      src: lista-jpos/{{ item }}
      dest: /home/reg/gd90/lista-jpos/
      owner: reg
      group: users
      mode: '0755'
     with_items:
       - FISCAL-PRINTER-NCR
       - FISCAL-PRINTER-TH320-230
   - name: Change to graphical pos linux
     shell: systemctl isolate graphical.target

